name = "Spartan Style"
license = "MIT"
licenselink = "https://github.com/u915/Spartan-Style/blob/master/LICENSE"
description = "Simple custom theme for HUGO"
homepage = "https://github.com/u915/Spartan-Style"
tags = [ "simple", "blog", "white" ]
features = [ "simple", "white" ]
min_version = "0.74.3"

[author]
name = "Daniel Cano Merchán"
homepage = "https://u915.net"
